# Import path and include to define URL patterns and include other URL configs
from django.urls import path, include

# Import DefaultRouter to automatically generate RESTful routes for the ViewSet
from rest_framework.routers import DefaultRouter

# Import the ReservationViewSet from views
from .views import ReservationViewSet

# Create a default router instance
router = DefaultRouter()

# Register the ReservationViewSet with the router
# This will automatically generate standard CRUD routes for reservations
router.register('', ReservationViewSet)

# Define the main URL patterns for this app
urlpatterns = [
    # Include all routes generated by the router
    path('', include(router.urls)),
]
